### ISSUE TITLE
Create wireframe for landing page

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#1]
# Overview

Design mobile friendly wireframe for landing page on Figma, basing the design on [arbitrum foundation grants][(https://www.google.com](https://arbitrum.foundation/grants)) page.

The brainstorming for this can be found [here](https://docs.google.com/document/d/1xMyEbqtiYlFLszTHU1TQOdPgiNLP2O08qFwCF1dvujI/edit).

## Tasks
- [x] Create initial draft
- [x] Iterate over initial draft
- [x] Get team feedback
- [x] implement feedback
