### ISSUE TITLE
Implement register page

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#10]
# Overview

Develop register page.

## Tasks
- [x] Create form with formik and yup
- [x] Handle fetch and posts
- [x] Autocomplete form if found (Draft or Published status)
- [x] add dynamic registration options
