### ISSUE TITLE
Change PlayFair font to EB Garamond

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#123]
# Overview

As suggested, we will try the [`EB Garamond`](https://fonts.google.com/specimen/EB+Garamond) serif font, replacing our current `PlayFair Display` and `PlayFair` fonts, buttons will keep the `Raleway` font

Embeded code for html will look like this:
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Raleway:wght@600&display=swap" rel="stylesheet">
```

And our font family should be updated at `global.styled.tsx`:
```css
--font-family-title: 'Playfair Display', serif;
--font-family-body: 'Playfair', serif;
--font-family-button: 'Raleway', sans-serif;
  ```

## Tasks
- [x] Update index.html with new google font
- [x] Update css root variable
- [ ] Update Figma desing (tbd)
