### ISSUE TITLE
Improve UI by replacing Button with IconButton

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#126]
# Overview
Add credential, Add publication and Add contributions should be replaced with a plain add icon `+` 
The icon can be found at [google icons](https://fonts.google.com/icons?icon.query=add)

An useful improvement would be to create a `IconButton` component that we can pass the icon url from our `public` folder, so we avoid cases like this:
```js
<Button onClick={() => removePublications(i)} $color="secondary">
  <div style={{ width: 24 }}>
    <img src={`/icons/trash-${theme}.svg`} height={24} width={24} />
  </div>
</Button>
```

```js
<Button
  onClick={() => {
    insertCredentialsGroup(fieldsCredentialsGroup.length, {
      credential: '',
      institution: '',
      field: '',
    });
  }}
>
  Add credential
</Button>
```

## Tasks
- [x] Create IconButton component
- [x] Add `+` icon to public folder (on `#fff` and `#222` colors)
- [x] Replace buttons with IconButtons
