### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/forum-frontend#16]
# overview
["wizard of oz" ](https://ewor.io/blog/wizard-of-oz-prototype/#:~:text=test%20their%20products.-,What%20Is%20Wizard%20of%20Oz%20Prototyping%3F,partially%E2%80%93controlled%20by%20another%20human.) home page. we want the home page to show the ui but it does not have to be connected to the backend.

## todo
- [x] QuestionOption cards (show text and vote button)
- [x] ForumQuestion title at the top of the page
- [x] Countdown timer to next cycle (general under the title) (can be time till tomorrow, does not have to come from backend)
- [x] vote and unvote interaction (should be reactive to total hearts in the nav bar)
