### ISSUE TITLE
Implement landing page wireframe

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#2]
# Overview

Develop the designed wireframe for landing page.

## Tasks
- [x] https://github.com/lexicongovernance/forum-frontend/issues/15
- [x] Integrate zupass auth
- [x] Link to register page
