### ISSUE TITLE
Test lexicon deployed instance

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#3]
# Overview

Test deployed instance

## Tasks
- [x] Create account
- [x] Register
- [x] Test the page on different devices and browsers
- [x] Try to break something
- [x] log out and log in

report in this issue any weird interactions

**Comment by MartinBenediktBusch** [comment]
We use MEV without defining it once. I.e. the first time we use MEV I would write Maximum Extractable Value (MEV)
On Page 4: "You can read more here" - link is missing in here.
On Page 4: I find the following sentence a bit weird: "The result should be to signal boost ideas which have support from a broad swathe of the community" Suggestion: "
The goal is to amplify ideas that enjoy widespread support within the community"
Register page: It is not possible to modify my information after the submission of the registration form. Usually, edits will be made by presenters on an ongoing basis (especially to the abstract).
